### ISSUE TITLE
Create Entities Transformation

### ISSUE THREAD

**Issue by Gauhar** [Botmock/sdk#581]
@rahulchauhan049  - Please add some description and plan here

**Comment by rahulchauhan049** [comment]
In this ticket, we are going to create a method that takes botmock entities and converts them to the following structure.
The entities is an array of objects. Each object will contain information like displayName of entity, value, and synonyms, etc.

```jsx
[
		{
      "displayName": "foodMenu",
      "kind": "KIND_MAP",
      "entities": [
          {
              "value": "pizza",
              "synonyms": ["pizza", "pimza"]
          },
          {
              "value": "burger",
              "synonyms": ["burger"]
          }
      ],
      "enableFuzzyExtraction": false,
      "redact": false
		}
]
```

**Comment by rahulchauhan049** [comment]
Dialogflow Automatically enables if it founds system entity used anywhere in any intent. 
We may need to find how we are going to map Existing entities of Botmock that does not exist in dialogflow CX
